# Generated by Django 4.2.27 on 2026-01-11 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('weibo', '微博'), ('social_truth', 'Social Truth'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=20, verbose_name='平台')),
                ('blogger_id', models.CharField(max_length=100, verbose_name='博主ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, max_length=200, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像URL')),
                ('homepage_url', models.URLField(blank=True, verbose_name='主页URL')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('followers_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('following_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('posts_count', models.IntegerField(default=0, verbose_name='微博数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='最后爬取时间')),
                ('last_post_id', models.CharField(blank=True, max_length=100, verbose_name='最后爬取的推文ID')),
                ('last_post_time', models.DateTimeField(blank=True, null=True, verbose_name='最后爬取的推文时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博主',
                'verbose_name_plural': '博主',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('weibo', '微博'), ('social_truth', 'Social Truth'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=20, verbose_name='平台')),
                ('post_id', models.CharField(max_length=100, verbose_name='推文ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('raw_content', models.TextField(blank=True, verbose_name='原始内容(JSON)')),
                ('images', models.TextField(blank=True, default='[]', verbose_name='图片URL列表(JSON)')),
                ('videos', models.TextField(blank=True, default='[]', verbose_name='视频URL列表(JSON)')),
                ('external_links', models.TextField(blank=True, default='[]', verbose_name='外部链接(JSON)')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('reposts_count', models.IntegerField(default=0, verbose_name='转发数')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('is_repost', models.BooleanField(default=False, verbose_name='是否转发')),
                ('original_post_id', models.CharField(blank=True, max_length=100, verbose_name='原推文ID')),
                ('original_post_url', models.URLField(blank=True, verbose_name='原推文链接')),
                ('content_hash', models.CharField(db_index=True, max_length=32, verbose_name='内容哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='crawler.blogger', verbose_name='博主')),
            ],
            options={
                'verbose_name': '推文',
                'verbose_name_plural': '推文',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('weibo', '微博'), ('social_truth', 'Social Truth'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='状态')),
                ('posts_found', models.IntegerField(default=0, verbose_name='发现推文数')),
                ('posts_new', models.IntegerField(default=0, verbose_name='新增推文数')),
                ('posts_duplicate', models.IntegerField(default=0, verbose_name='重复推文数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('blogger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_logs', to='crawler.blogger', verbose_name='博主')),
            ],
            options={
                'verbose_name': '爬虫日志',
                'verbose_name_plural': '爬虫日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogger',
            index=models.Index(fields=['platform', 'blogger_id'], name='crawler_blo_platfor_9466a7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogger',
            index=models.Index(fields=['is_active'], name='crawler_blo_is_acti_b8e6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='blogger',
            index=models.Index(fields=['last_crawled_at'], name='crawler_blo_last_cr_ac7374_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blogger',
            unique_together={('platform', 'blogger_id')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['platform', 'post_id'], name='crawler_pos_platfor_6c5045_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_hash'], name='crawler_pos_content_9ed507_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['blogger', 'published_at'], name='crawler_pos_blogger_b3dbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='crawler_pos_publish_8e5562_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('platform', 'post_id')},
        ),
        migrations.AddIndex(
            model_name='crawlerlog',
            index=models.Index(fields=['platform'], name='crawler_cra_platfor_3bd669_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerlog',
            index=models.Index(fields=['status'], name='crawler_cra_status_1f689f_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerlog',
            index=models.Index(fields=['-started_at'], name='crawler_cra_started_bda44b_idx'),
        ),
    ]
